---
# tasks to import cert
  - name: Enforce password history
    community.windows.win_security_policy:
      section: System Access
      key: PasswordHistorySize
      value: 24
#    become: true
#    become_method: runas
#    become_user: yks21adm 