---
# Enforce password history
  - name: Enforce password history
    community.windows.win_security_policy:
      section: System Access
      key: PasswordHistorySize
      value: 24
# Set the maximum password age
  - name: Set the maximum password age
    community.windows.win_security_policy:
      section: System Access
      key: MaximumPasswordAge
      value: 90
  - name: Set the minimum password age
    community.windows.win_security_policy:
      section: System Access
      key: MinimumPasswordAge
      value: 3
  - name: Minimum password length
    community.windows.win_security_policy:
      section: System Access
      key: MinimumPasswordLength
      value: 14
  - name: Ensure Relax minimum password length limits is set to Enabled
    community.windows.win_security_policy:
      section: System Access
      key: PasswordComplexity
      value: 1
#    become: true
#    become_method: runas
#    become_user: yks21adm 